builder:
  build: ./
  stdin_open: true
  tty: true
  dockerfile: docker/Dockerfile.builder
  links:
    - ganache
  environment:
    SET_CONTAINER_TIMEZONE: 'True'
    CONTAINER_TIMEZONE: Europe/Prague
  env_file:
    .env
  volumes:
    - "./build/:/marblegame/build"
    - "./src/contracts:/marblegame/contracts"
    - "./src/contracts-flatten:/marblegame/contracts-flatten"
    - "./src/migrations:/marblegame/migrations"
    - "./src/test:/marblegame/test"
    - "./src/scripts:/marblegame/scripts"
    - "./scripts_container:/marblegame/scripts_container"
    - "./charts:/marblegame/charts"
ganache:
  image: trufflesuite/ganache-cli:v6.12.2
  command: ganache -p 8545 -h 0.0.0.0
  environment:
    SET_CONTAINER_TIMEZONE: 'True'
    CONTAINER_TIMEZONE: Europe/Prague
